### ISSUE TITLE
Function that convert a `KnowledgeGraph` to a `DataFrame`

### ISSUE THREAD

**Issue by Tazoeur** [torchkge-team/torchkge#205]
I had to implement this function for the project I am currently working on and I guess it could be handy to someone else.

I don't really know in which file this function would be at its best place but I would be glad to create a pull request if someone has a good idea about it.
Also if you have remarks/advices about the implementation do not hesitate to point them to me.

```python
def kg2df(kg: KnowledgeGraph) -> pd.DataFrame:
    """
    Revert a torchKGE `KnowledgeGraph` into a pandas `DataFrame`.

    :param kg: A knowledge graph.
    :return: A dataframe containing the same information than the knowledge graph.
    """
    ix2rel = dict([(ix, rel) for rel, ix in kg.rel2ix.items()])
    ix2ent = dict([(ix, rel) for rel, ix in kg.ent2ix.items()])

    df = pd.DataFrame({'from': kg.head_idx, 'rel': kg.relations, 'to': kg.tail_idx})

    df['from'] = df['from'].map(ix2ent)
    df['rel'] = df['rel'].map(ix2rel)
    df['to'] = df['to'].map(ix2ent)

    return df
```

**Comment by armand33** [comment]
Hi @Tazoeur, this feature has already been added in PR https://github.com/torchkge-team/torchkge/pull/195 and then fixed in PR https://github.com/torchkge-team/torchkge/pull/197 in the form of a `get_df` method of the `KnowledgeGraph` object. This has been merged in master but has not been released yet.
